import { DBUser, Param, Company } from '@classes/index'

export enum ActionTypes {
  SUBMITTING = '@@users/SUBMITTING',
  GET_USERS_REQUEST = '@@users/GET_USERS_REQUEST',
  GET_USERS_SUCCESS = '@@users/GET_USERS_SUCCESS',
  GET_USERS_FAILURE = '@@users/GET_USERS_FAILURE',
  ADD_USER_REQUEST = '@@users/ADD_TERRITORY_REQUEST',
  ADD_USER_SUCCESS = '@@users/ADD_TERRITORY_SUCCESS',
  ADD_USER_FAILURE = '@@users/ADD_TERRITORY_FAILURE',
  UPDATE_USER_REQUEST = '@@users/UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS = '@@users/UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE = '@@users/UPDATE_USER_FAILURE',
  DELETE_USER_REQUEST = '@@users/DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS = '@@users/DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE = '@@users/DELETE_USER_FAILURE',
  EXPORT_USERS_REQUEST = '@@users/EXPORT_USERS_REQUEST',
  EXPORT_USERS_SUCCESS = '@@users/EXPORT_USERS_SUCCESS',
  EXPORT_USERS_FAILURE = '@@users/EXPORT_USERS_FAILURE',
  CLEAR_STATES = '@@users/CLEAR_STATES',
  SET_ACTIVE_LINK = '@@users/SET_ACTIVE_LINK',
  SET_USER = '@@users/SET_USER',
  SET_QUERY_PARAMS = '@@users/SET_QUERY_PARAMS',
  GET_USERS_SEARCH_REQUEST = '@@users/GET_USERS_SEARCH_REQUEST',
  GET_USERS_SEARCH_SUCCESS = '@@users/GET_USERS_SEARCH_SUCCESS',
  GET_USERS_SEARCH_FAILURE = '@@users/GET_USERS_SEARCH_FAILURE',
  CLEAR_SEARCHED_USERS = '@@users/CLEAR_SEARCHED_USERS',
  ASSIGN_USER_TERRITORY_REQUEST = '@@users/ASSIGN_USER_TERRITORY_REQUEST',
  ASSIGN_USER_TERRITORY_SUCCESS = '@@users/ASSIGN_USER_TERRITORY_SUCCESS',
  ASSIGN_USER_TERRITORY_FAILURE = '@@users/ASSIGN_USER_TERRITORY_FAILURE',
  UPDATE_USER_TERRITORY_REQUEST = '@@users/UPDATE_USER_TERRITORY_REQUEST',
  UPDATE_USER_TERRITORY_SUCCESS = '@@users/UPDATE_USER_TERRITORY_SUCCESS',
  UPDATE_USER_TERRITORY_FAILURE = '@@users/UPDATE_USER_TERRITORY_FAILURE',
  GET_USER_REQUEST = '@@users/GET_USER_REQUEST',
  GET_USER_SUCCESS = '@@users/GET_USER_SUCCESS',
  GET_USER_FAILURE = '@@users/GET_USER_FAILURE',
  CHANGE_PASSWORD_REQUEST = '@@users/CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS = '@@users/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE = '@@users/CHANGE_PASSWORD_FAILURE',
  GET_COMPANY_REQUEST = '@@users/GET_COMPANY_REQUEST',
  GET_COMPANY_SUCCESS = '@@users/GET_COMPANY_SUCCESS',
  GET_COMPANY_FAILURE = '@@users/GET_COMPANY_FAILURE',
  ADD_COMPANY_REQUEST = '@@users/ADD_COMPANY_REQUEST',
  ADD_COMPANY_SUCCESS = '@@users/ADD_COMPANY_SUCCESS',
  ADD_COMPANY_FAILURE = '@@users/ADD_COMPANY_FAILURE',
  UPDATE_COMPANY_REQUEST = '@@users/UPDATE_COMPANY_REQUEST',
  UPDATE_COMPANY_SUCCESS = '@@users/UPDATE_COMPANY_SUCCESS',
  UPDATE_COMPANY_FAILURE = '@@users/UPDATE_COMPANY_FAILURE'
}

export type UserState = {
  readonly isSubmitting: boolean
  readonly errors: any
  readonly users: DBUser[]
  readonly loading: boolean
  readonly isExporting: boolean
  readonly isSucceeded: boolean
  readonly changePassword: boolean
  readonly activeLink: string
  readonly isDeleted: boolean
  readonly user: DBUser | null
  readonly params: Param
  readonly count: number
  readonly searchedUsers: DBUser[]
  readonly company: Company | null
}
